export const ALL_BOOKS_REQESTS = "ALL_BOOKS_REQESTS";
export const ALL_BOOKS_SUCCESS = "ALL_BOOKS_SUCCESS";
export const ALL_BOOKS_FAIL = "ALL_BOOKS_FAIL";

export const ALL_BOOK_DETAILS_REQESTS = "ALL_BOOK_DETAILS_REQESTS";
export const ALL_BOOK_DETAILS_SUCCESS = "ALL_BOOK_DETAILS_SUCCESS";
export const ALL_BOOK_DETAILS_FAIL = "ALL_BOOK_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";